services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - daccvo
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mongod:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    networks:
      - daccvo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - daccvo
    ports:
      - 6379:6379
    volumes:
      - './data/redis_data:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  chefconnect:
    image: chefconnect:latest
    container_name: chefconnect
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - daccvo
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - .env

networks:
  daccvo:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16



